name: Upload Python Package to TestPyPI
on:
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install Java 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: Display Pip and Python version
      run: python -m pip -V

    - name: Setting up project
      run: make setup

    - name: Setting up virtual environment
      run: make setup_venv

    - name: Building package
      run: make build

    - name: Installing proactive from dist
      run: make install

    - name: Check proactive version
      run: make print_version

    - name: Publish to TestPyPI
      env:
        TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.TESTPYPI_TOKEN }}
      run: make publish_test_using_secrets
